/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "turtlpass.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(turtlpass_GeneratePasswordParams, turtlpass_GeneratePasswordParams, AUTO)


PB_BIND(turtlpass_InitializeSeedParams, turtlpass_InitializeSeedParams, AUTO)


PB_BIND(turtlpass_DeviceInfo, turtlpass_DeviceInfo, AUTO)


PB_BIND(turtlpass_Command, turtlpass_Command, AUTO)


PB_BIND(turtlpass_Response, turtlpass_Response, 2)









