/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TURTLPASS_TURTLPASS_PB_H_INCLUDED
#define PB_TURTLPASS_TURTLPASS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Supported commands */
typedef enum _turtlpass_CommandType {
    turtlpass_CommandType_UNKNOWN = 0, /* Default / invalid command */
    turtlpass_CommandType_GET_DEVICE_INFO = 1, /* Returns version, seed state, etc. */
    turtlpass_CommandType_INITIALIZE_SEED = 2, /* Store seed for password derivation */
    turtlpass_CommandType_GENERATE_PASSWORD = 3, /* Derives a password based on parameters */
    turtlpass_CommandType_FACTORY_RESET = 4 /* Resets device to default state (no seeds) */
} turtlpass_CommandType;

/* Character set options for password generation */
typedef enum _turtlpass_Charset {
    turtlpass_Charset_LETTERS_ONLY = 0,
    turtlpass_Charset_NUMBERS_ONLY = 1,
    turtlpass_Charset_LETTERS_NUMBERS = 2,
    turtlpass_Charset_LETTERS_NUMBERS_SYMBOLS = 3
} turtlpass_Charset;

/* Error codes for responses */
typedef enum _turtlpass_ErrorCode {
    turtlpass_ErrorCode_NONE = 0, /* No error */
    turtlpass_ErrorCode_INVALID_COMMAND = 1,
    turtlpass_ErrorCode_INVALID_PARAMS = 2,
    turtlpass_ErrorCode_INVALID_ENTROPY_LENGTH = 3,
    turtlpass_ErrorCode_INVALID_PASSWORD_LENGTH = 4,
    turtlpass_ErrorCode_INVALID_SEED_LENGTH = 5,
    turtlpass_ErrorCode_SEED_NOT_INITIALIZED = 6,
    turtlpass_ErrorCode_PASSWORD_FAILED = 7,
    turtlpass_ErrorCode_PROTO_DECODING_FAILED = 8,
    turtlpass_ErrorCode_PROTO_ENCODING_FAILED = 9,
    turtlpass_ErrorCode_INTERNAL_ERROR = 10
} turtlpass_ErrorCode;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) turtlpass_GeneratePasswordParams_entropy_t;
/* Parameters for password generation */
typedef struct _turtlpass_GeneratePasswordParams {
    turtlpass_GeneratePasswordParams_entropy_t entropy; /* Entropy source (1–64 bytes) */
    uint32_t length; /* Desired password length (default: 100 chars) */
    turtlpass_Charset charset; /* Character set to use (default: LETTERS_NUMBERS) */
} turtlpass_GeneratePasswordParams;

typedef PB_BYTES_ARRAY_T(64) turtlpass_InitializeSeedParams_seed_t;
/* Parameters for initializing the device seed */
typedef struct _turtlpass_InitializeSeedParams {
    turtlpass_InitializeSeedParams_seed_t seed; /* Seed data to store securely in emulated EEPROM */
} turtlpass_InitializeSeedParams;

typedef PB_BYTES_ARRAY_T(16) turtlpass_DeviceInfo_unique_board_id_t;
typedef struct _turtlpass_DeviceInfo {
    char turtlpass_version[32]; /* e.g., "3.0.0" */
    char arduino_version[16]; /* e.g., "10810" */
    char compiler_version[32]; /* e.g., "14.3.0" */
    char nanopb_version[32]; /* e.g., "nanopb-1.0.0" */
    char board_name[32]; /* e.g., "pico" */
    turtlpass_DeviceInfo_unique_board_id_t unique_board_id; /* 16-byte unique MCU identifier */
} turtlpass_DeviceInfo;

/* Main command sent from host to MCU */
typedef struct _turtlpass_Command {
    turtlpass_CommandType type;
    pb_size_t which_parameters;
    union {
        turtlpass_GeneratePasswordParams gen_pass;
        turtlpass_InitializeSeedParams init_seed;
    } parameters;
} turtlpass_Command;

typedef PB_BYTES_ARRAY_T(512) turtlpass_Response_data_t;
/* Response sent from MCU to host */
typedef struct _turtlpass_Response {
    bool success; /* True if command succeeded */
    turtlpass_ErrorCode error; /* Error code (NONE if success=true) */
    bool has_device_info;
    turtlpass_DeviceInfo device_info; /* Structured info for GET_DEVICE_INFO */
    turtlpass_Response_data_t data; /* Optional command-specific data */
} turtlpass_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _turtlpass_CommandType_MIN turtlpass_CommandType_UNKNOWN
#define _turtlpass_CommandType_MAX turtlpass_CommandType_FACTORY_RESET
#define _turtlpass_CommandType_ARRAYSIZE ((turtlpass_CommandType)(turtlpass_CommandType_FACTORY_RESET+1))

#define _turtlpass_Charset_MIN turtlpass_Charset_LETTERS_ONLY
#define _turtlpass_Charset_MAX turtlpass_Charset_LETTERS_NUMBERS_SYMBOLS
#define _turtlpass_Charset_ARRAYSIZE ((turtlpass_Charset)(turtlpass_Charset_LETTERS_NUMBERS_SYMBOLS+1))

#define _turtlpass_ErrorCode_MIN turtlpass_ErrorCode_NONE
#define _turtlpass_ErrorCode_MAX turtlpass_ErrorCode_INTERNAL_ERROR
#define _turtlpass_ErrorCode_ARRAYSIZE ((turtlpass_ErrorCode)(turtlpass_ErrorCode_INTERNAL_ERROR+1))

#define turtlpass_GeneratePasswordParams_charset_ENUMTYPE turtlpass_Charset



#define turtlpass_Command_type_ENUMTYPE turtlpass_CommandType

#define turtlpass_Response_error_ENUMTYPE turtlpass_ErrorCode


/* Initializer values for message structs */
#define turtlpass_GeneratePasswordParams_init_default {{0, {0}}, 0, _turtlpass_Charset_MIN}
#define turtlpass_InitializeSeedParams_init_default {{0, {0}}}
#define turtlpass_DeviceInfo_init_default        {"", "", "", "", "", {0, {0}}}
#define turtlpass_Command_init_default           {_turtlpass_CommandType_MIN, 0, {turtlpass_GeneratePasswordParams_init_default}}
#define turtlpass_Response_init_default          {0, _turtlpass_ErrorCode_MIN, false, turtlpass_DeviceInfo_init_default, {0, {0}}}
#define turtlpass_GeneratePasswordParams_init_zero {{0, {0}}, 0, _turtlpass_Charset_MIN}
#define turtlpass_InitializeSeedParams_init_zero {{0, {0}}}
#define turtlpass_DeviceInfo_init_zero           {"", "", "", "", "", {0, {0}}}
#define turtlpass_Command_init_zero              {_turtlpass_CommandType_MIN, 0, {turtlpass_GeneratePasswordParams_init_zero}}
#define turtlpass_Response_init_zero             {0, _turtlpass_ErrorCode_MIN, false, turtlpass_DeviceInfo_init_zero, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define turtlpass_GeneratePasswordParams_entropy_tag 1
#define turtlpass_GeneratePasswordParams_length_tag 2
#define turtlpass_GeneratePasswordParams_charset_tag 3
#define turtlpass_InitializeSeedParams_seed_tag  1
#define turtlpass_DeviceInfo_turtlpass_version_tag 1
#define turtlpass_DeviceInfo_arduino_version_tag 2
#define turtlpass_DeviceInfo_compiler_version_tag 3
#define turtlpass_DeviceInfo_nanopb_version_tag  4
#define turtlpass_DeviceInfo_board_name_tag      5
#define turtlpass_DeviceInfo_unique_board_id_tag 6
#define turtlpass_Command_type_tag               1
#define turtlpass_Command_gen_pass_tag           2
#define turtlpass_Command_init_seed_tag          3
#define turtlpass_Response_success_tag           1
#define turtlpass_Response_error_tag             2
#define turtlpass_Response_device_info_tag       3
#define turtlpass_Response_data_tag              4

/* Struct field encoding specification for nanopb */
#define turtlpass_GeneratePasswordParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    entropy,           1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2) \
X(a, STATIC,   SINGULAR, UENUM,    charset,           3)
#define turtlpass_GeneratePasswordParams_CALLBACK NULL
#define turtlpass_GeneratePasswordParams_DEFAULT NULL

#define turtlpass_InitializeSeedParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    seed,              1)
#define turtlpass_InitializeSeedParams_CALLBACK NULL
#define turtlpass_InitializeSeedParams_DEFAULT NULL

#define turtlpass_DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   turtlpass_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   arduino_version,   2) \
X(a, STATIC,   SINGULAR, STRING,   compiler_version,   3) \
X(a, STATIC,   SINGULAR, STRING,   nanopb_version,    4) \
X(a, STATIC,   SINGULAR, STRING,   board_name,        5) \
X(a, STATIC,   SINGULAR, BYTES,    unique_board_id,   6)
#define turtlpass_DeviceInfo_CALLBACK NULL
#define turtlpass_DeviceInfo_DEFAULT NULL

#define turtlpass_Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (parameters,gen_pass,parameters.gen_pass),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (parameters,init_seed,parameters.init_seed),   3)
#define turtlpass_Command_CALLBACK NULL
#define turtlpass_Command_DEFAULT NULL
#define turtlpass_Command_parameters_gen_pass_MSGTYPE turtlpass_GeneratePasswordParams
#define turtlpass_Command_parameters_init_seed_MSGTYPE turtlpass_InitializeSeedParams

#define turtlpass_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, UENUM,    error,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       3) \
X(a, STATIC,   SINGULAR, BYTES,    data,              4)
#define turtlpass_Response_CALLBACK NULL
#define turtlpass_Response_DEFAULT NULL
#define turtlpass_Response_device_info_MSGTYPE turtlpass_DeviceInfo

extern const pb_msgdesc_t turtlpass_GeneratePasswordParams_msg;
extern const pb_msgdesc_t turtlpass_InitializeSeedParams_msg;
extern const pb_msgdesc_t turtlpass_DeviceInfo_msg;
extern const pb_msgdesc_t turtlpass_Command_msg;
extern const pb_msgdesc_t turtlpass_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define turtlpass_GeneratePasswordParams_fields &turtlpass_GeneratePasswordParams_msg
#define turtlpass_InitializeSeedParams_fields &turtlpass_InitializeSeedParams_msg
#define turtlpass_DeviceInfo_fields &turtlpass_DeviceInfo_msg
#define turtlpass_Command_fields &turtlpass_Command_msg
#define turtlpass_Response_fields &turtlpass_Response_msg

/* Maximum encoded size of messages (where known) */
#define TURTLPASS_TURTLPASS_PB_H_MAX_SIZE        turtlpass_Response_size
#define turtlpass_Command_size                   78
#define turtlpass_DeviceInfo_size                167
#define turtlpass_GeneratePasswordParams_size    74
#define turtlpass_InitializeSeedParams_size      66
#define turtlpass_Response_size                  689

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
